### PR TITLE
Buildvignette

### LINKED ISSUE #10: Code coverage
Now that codecov is added, we should use improve the code coverage, *i.e.* we should implement tests in the `test` folder (see http://r-pkgs.had.co.nz/tests.html). 

I may be tricky as we need a token to perform most of the tests (making this issue related to #9).

### PR DESCRIPTION
**Pull request by KevCaz**
This PR includes:

- :book: outline the vignettes.
- :book: few edits in README.
- :book: add `inst/ms` and `paper.md` within it is more or less the `.md` file found on https://joss.theoj.org/about#author_guidelines.
- :hammer: `spplus_baseurl()` renamed `sppplus_baseurl()` to meet our naming convention.
- :hammer: `sppplus_taxonconcept()` reviewed to take multi taxon concept entries into account.
- :hammer: `sppplus_simplify()` now tests dimensions of the data.table passed before doing anything to prevent any issue with 0x0 data.table objects.
- :shield: add a test for multi taxon concept entries in `sppplus_taxonconcept()`.
- :shield: another extra unit testing for `sppplus_taxonconcept()` to test not listed taxa.
- :shield: few unit testings of `zzz.R` helper functions.
- I am satisfied with the current code coverage, so let's close #10

### CODE REVIEW

**Comment by KevCaz** [comment]
@ibartomeus all good. @ibartomeus @JonasGeschke I let you guys finish up the vignette. I think it will be a good opportunity for you to review code and documentation!

**Comment by KevCaz** [comment]
@ibartomeus will you find some time this week to work on the vignette?

**Comment by ibartomeus** [comment]
Sorry, @KevCaz, I thought I could do it, but we are putting together a large proposal which is taking all my time. As soon as possible. I promise.

**Comment by KevCaz** [comment]
No worries!! 

In the meanwhile I'd merge this so a newer version is made available!

**Pull request merged**
