### PR TITLE
httr / json and more

### LINKED ISSUE #2: change Rcurl to httr

### LINKED ISSUE #4: rworld, should we include it?
To keep the package as light as possible, I would recommend to use `rworldmap` in a vignette but not in the package. Just a thought.

### LINKED ISSUE #6: Wrong information returned
Hi developers,

sometimes some species have a wrong and correct appendix value returned, like in the example bellow.
I did not identify any pattern in this kind of error.

Cheers!
Fred

`sppplus_taxonconcept(key, query = "Amazilia versicolor")`

1   3210 Amazilia versicolor    II
2  65789 Amazilia versicolor  NA

`sessionInfo()`

R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252   
[3] LC_MONETARY=Portuguese_Brazil.1252 LC_NUMERIC=C                      
[5] LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] tcltk     stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.4 citesr_0.0.1   

loaded via a namespace (and not attached):
[1] compiler_3.4.2  tools_3.4.2     withr_2.1.1     RCurl_1.95-4.10 memoise_1.1.0  
[6] digest_0.6.12   bitops_1.0-6    XML_3.98-1.9

### PR DESCRIPTION
**Pull request by KevCaz**
- citesr now uses the `httr` package instead of `Rcurl` - closes #2 ;
- citesr now uses the default output format of the API, *i.e*  **json**;
- `sppplus_connect()` has been droped, a variable `token` is used instead and
this **must be reviewed in future development** (see https://cran.r-project.org/web/packages/httr/vignettes/secrets.html
and https://cran.r-project.org/web/packages/googlesheets/vignettes/managing-auth-tokens.html)
- all output are now `data.table` objects or lists of `data.table`;
- handy functions are stored in `zzz.R` (inspired by the taxize package);
- `joinCountryData2Map()` is removed, to me this should be included in the vignette rather than a function of the package, close #4;
- `README.Rmd` is added and used to provide examples in the README.md (it should be
rendered with the `rmarkdown` package).

Tthese changes will especially be useful if we intend to submit our package to
Ropenscience. Also the bug reported in #6  is fixed, I therefore close #6.

### CODE REVIEW

**Comment by ibartomeus** [comment]
Kevin you are awesome! Thanks. @JonasGeschke I think we can send it to ropensci for review already? Should I contact sckott?

**Comment by JonasGeschke** [comment]
Hi guys, I try to follow up by reading the emails. The package looks great, good process!
I will do the EU legislation API during next week. Or would you leave that for ropensci review? As you worked on the package today, you know better whats the status. I would need to check this next week (on the train for two days). But if you want to start with ropensci review now, go for it!

**Comment by KevCaz** [comment]
I think a little bit of work is still needed - can I ask for one more week (one more week-end actually) before we proceed? 

That being said, asking for a first look at our package from Ropenscience people would be great as they can give us some advice about what should be our next steps! 
 
By the way, I can handle the EU-legislation quickly today so that you guys perform a kind of internal review next week if you have time, of course.

**Comment by KevCaz** [comment]
I'll open a couple of issues so we keep track of few things.

**Comment by JonasGeschke** [comment]
From my side, one more week plus week-end sounds good before proceeding.
Think so too, a clarification and advice on the next steps from Ropenscience would be good. You guys have some contacts there, right?

If you like you can start with the EU legistaltion, sure. Should not be too much work, too, as the API is generally built up similar to the others, so ”only the outcomes“ need to be edited. Then I can check what you started with next week.

**Comment by ibartomeus** [comment]
Good, I'll do an informal first contact with ropnsci to ask about the process without staring it yet.

**Comment by KevCaz** [comment]
Good to see that this is moving forward ! 

Thanks @ibartomeus @JonasGeschke !

**Pull request merged**
